<?php

return [
    'roles' => ['admin', 'manager', 'user'],
    'modules' => ['books', 'products', 'courses', 'users', 'role-permissions', 'permissions'],
    'actions' => ['view', 'create', 'edit', 'delete'],
    'defaults' => [
        'admin' => [
            'books.view' => true,
            'books.create' => true,
            'books.edit' => true,
            'books.delete' => true,
            'products.view' => true,
            'products.create' => true,
            'products.edit' => true,
            'products.delete' => true,
            'courses.view' => true,
            'courses.create' => true,
            'courses.edit' => true,
            'courses.delete' => true,
            'users.view' => true,
            'users.create' => true,
            'users.edit' => true,
            'users.delete' => true,
            'role-permissions.view' => true,
            'role-permissions.create' => true,
            'role-permissions.edit' => true,
            'role-permissions.delete' => true,
            'permissions.view' => true,
            'permissions.create' => true,
            'permissions.edit' => true,
            'permissions.delete' => true,
        ],
        'manager' => [
            'books.view' => true,
            'books.create' => true,
            'books.edit' => true,
            'books.delete' => false,
            'products.view' => true,
            'products.create' => true,
            'products.edit' => true,
            'products.delete' => false,
            'courses.view' => true,
            'courses.create' => true,
            'courses.edit' => true,
            'courses.delete' => false,
            'users.view' => false,
            'users.create' => false,
            'users.edit' => false,
            'users.delete' => false,
            'role-permissions.view' => false,
            'role-permissions.create' => false,
            'role-permissions.edit' => false,
            'role-permissions.delete' => false,
            'permissions.view' => false,
            'permissions.create' => false,
            'permissions.edit' => false,
            'permissions.delete' => false,
        ],
        'user' => [
            'books.view' => true,
            'books.create' => false,
            'books.edit' => false,
            'books.delete' => false,
            'products.view' => true,
            'products.create' => false,
            'products.edit' => false,
            'products.delete' => false,
            'courses.view' => true,
            'courses.create' => false,
            'courses.edit' => false,
            'courses.delete' => false,
            'users.view' => false,
            'users.create' => false,
            'users.edit' => false,
            'users.delete' => false,
            'role-permissions.view' => false,
            'role-permissions.create' => false,
            'role-permissions.edit' => false,
            'role-permissions.delete' => false,
            'permissions.view' => false,
            'permissions.create' => false,
            'permissions.edit' => false,
            'permissions.delete' => false,
        ],
    ],
];
