export const MODULES = ['books', 'products', 'courses', 'reports', 'users']
export const ACTIONS = ['view', 'create', 'edit', 'delete']

export const DEFAULT_ROLE_PERMISSIONS = {
  admin: {
    'books.view': true,
    'books.create': true,
    'books.edit': true,
    'books.delete': true,
    'products.view': true,
    'products.create': true,
    'products.edit': true,
    'products.delete': true,
    'courses.view': true,
    'courses.create': true,
    'courses.edit': true,
    'courses.delete': true,
    'reports.view': true,
    'users.view': true,
    'users.create': true,
    'users.edit': true,
    'users.delete': true,
  },
  manager: {
    'books.view': true,
    'books.create': true,
    'books.edit': true,
    'books.delete': false,
    'products.view': true,
    'products.create': true,
    'products.edit': true,
    'products.delete': false,
    'courses.view': true,
    'courses.create': true,
    'courses.edit': true,
    'courses.delete': false,
    'reports.view': true,
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.delete': false,
  },
  user: {
    'books.view': true,
    'books.create': false,
    'books.edit': false,
    'books.delete': false,
    'products.view': true,
    'products.create': false,
    'products.edit': false,
    'products.delete': false,
    'courses.view': true,
    'courses.create': false,
    'courses.edit': false,
    'courses.delete': false,
    'reports.view': false,
    'users.view': false,
    'users.create': false,
    'users.edit': false,
    'users.delete': false,
  },
}
